### ISSUE TITLE
fetch +e doesn't always record revision of a package

### ISSUE THREAD

**Issue by kaey** [kardianos/govendor#101]
govendor version ab600ff

add +e works fine, but I have a problem with fetch.
Repro (let me know if you need any other information):
```
$ mkdir usr2
$ export GOPATH=/home/k.kulikov/usr2
$ go get -d -v github.com/influxdata/telegraf
github.com/influxdata/telegraf (download)
github.com/influxdata/influxdb (download)
$ cd usr2/src/github.com/influxdata/telegraf/
$ govendor init
$ mcedit vendor/vendor.json # Add ignore appengine build tag
$ govendor fetch +e

#####
{
        "comment": "",
        "ignore": "test appengine",
        "package": [
                {
                        "path": "github.com/influxdata/influxdb/models",
                        "revision": ""
                },
                {
                        "checksumSHA1": "TjRR6XvQdNHPNBb6ICDJ0pAM4Io=",
                        "path": "github.com/influxdata/influxdb/pkg/escape",
                        "revision": "9f2b1ee15199538ba4c92d5a2a68d5646b9b9aa7",
                        "revisionTime": "2016-03-16T20:31:28-04:00"
                },
                {
                        "path": "github.com/influxdata/influxdb/pkg/escape",
                        "revision": ""
                }
        ]
}
#####

$ govendor fetch github.com/influxdata/influxdb/models

#####
{
        "comment": "",
        "ignore": "test appengine",
        "package": [
                {
                        "checksumSHA1": "YyYBOzgU7iczsMEe66OH1wBFCUQ=",
                        "path": "github.com/influxdata/influxdb/models",
                        "revision": "9f2b1ee15199538ba4c92d5a2a68d5646b9b9aa7",
                        "revisionTime": "2016-03-16T20:31:28-04:00"
                },
                {
                        "checksumSHA1": "TjRR6XvQdNHPNBb6ICDJ0pAM4Io=",
                        "path": "github.com/influxdata/influxdb/pkg/escape",
                        "revision": "9f2b1ee15199538ba4c92d5a2a68d5646b9b9aa7",
                        "revisionTime": "2016-03-16T20:31:28-04:00"
                },
                {
                        "path": "github.com/influxdata/influxdb/pkg/escape",
                        "revision": ""
                }
        ]
}
#####

$ govendor remove +v
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x8a22e0, 0xc82000e170)
        /home/k.kulikov/local/go16/src/runtime/panic.go:464 +0x3fa
github.com/kardianos/govendor/vendorfile.(*File).toAll(0xc820013100)
        /home/k.kulikov/usr/src/github.com/kardianos/govendor/vendorfile/file.go:230 +0x7dc
github.com/kardianos/govendor/vendorfile.(*File).Marshal(0xc820013100, 0x7fa43844d958, 0xc8202ea9a0, 0x0, 0x0)
        /home/k.kulikov/usr/src/github.com/kardianos/govendor/vendorfile/file.go:259 +0xb9
github.com/kardianos/govendor/context.(*Context).WriteVendorFile(0xc820122000, 0x0, 0x0)
        /home/k.kulikov/usr/src/github.com/kardianos/govendor/context/vendorFile.go:27 +0x14f
github.com/kardianos/govendor/run.Modify(0x7fa43844d1c0, 0xc82002c010, 0xc82000a3e0, 0x1, 0x1, 0x3, 0x7fa43844d798, 0xc8203dfda7, 0xc81fffa887, 0x0, ...)
        /home/k.kulikov/usr/src/github.com/kardianos/govendor/run/modify.go:212 +0x17ff
github.com/kardianos/govendor/run.Run(0x7fa43844d1c0, 0xc82002c010, 0xc82000a3c0, 0x3, 0x3, 0x7fa43844d798, 0xc8203dfda7, 0x10, 0x0, 0x0)
        /home/k.kulikov/usr/src/github.com/kardianos/govendor/run/run.go:72 +0x590
main.main()
        /home/k.kulikov/usr/src/github.com/kardianos/govendor/main.go:34 +0x475
```

**Comment by kardianos** [comment]
Looks like there are several bugs in here. eeep!

I'll look into. Thanks for the report.

**Comment by kardianos** [comment]
There were two issues here. One was resolved in another issue, the remove was resolved here.

You probably want the command `govendor fetch +out` to get both external and missing.
