### ISSUE TITLE
`govendor remove` panics: "should be listed internally but is not"

### ISSUE THREAD

**Issue by jacobsa** [kardianos/govendor#27]
I receive the following panic when I attempt to `govendor remove` a dependency:

```
jacobsa@jacobsa-macpro:~/go/src/github.com/googlecloudplatform/gcsfuse (master) [1] % go env | grep VENDOR
GO15VENDOREXPERIMENT="1"


jacobsa@jacobsa-macpro:~/go/src/github.com/googlecloudplatform/gcsfuse (master)% govendor list github.com/jacobsa/fuse
v github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/fuse [github.com/jacobsa/fuse]


jacobsa@jacobsa-macpro:~/go/src/github.com/googlecloudplatform/gcsfuse (master)% govendor remove  github.com/jacobsa/fuse
panic: Package "github.com/jacobsa/fuse" should be listed internally but is not.

goroutine 1 [running]:
github.com/kardianos/govendor/context.(*Context).ModifyImport(0x82047c000, 0x7fff5fbffa50, 0x17, 0x82042a303, 0x0, 0x0)
        /Users/jacobsa/go/src/github.com/kardianos/govendor/context/context.go:333 +0x730
main.run(0x88205a1380, 0x82043a008, 0x82042e150, 0x3, 0x3, 0x7405, 0x0, 0x0)
        /Users/jacobsa/go/src/github.com/kardianos/govendor/run.go:268 +0x93f
main.main()
        /Users/jacobsa/go/src/github.com/kardianos/govendor/main.go:14 +0x80
```

**Comment by jacobsa** [comment]
(Reproduce with GoogleCloudPlatform/gcsfuse@818d87d98848695a1f30e1710b6d3f8182b7329e using `govendor` at 9de80febcf158338d5eb650b395315d8d4a72a6e.)
