### ISSUE TITLE
govendor test hangs

### ISSUE THREAD

**Issue by dominicbarnes** [kardianos/govendor#337]
As of today's commit (cf990b21edc17bba6be732a3cbeb357e0c70f520) any attempt to use `govendor test` hangs indefinitely. If I remove the aforementioned commit from my git history and rebuild, the command runs normally again.

```bash
$ go version
go version go1.8.3 darwin/amd64
```

```bash
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/dominic/dev"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vs/fg8m4n3974b3bt33gswwv84r0000gn/T/go-build024708252=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

**Comment by kardianos** [comment]
Thanks for the report. Will look into ASAP.

**Comment by dominicbarnes** [comment]
I started the command and then killed it with `-ABRT`, here is the dump I saw:

```
SIGABRT: abort
PC=0x105b1db m=0 sigcode=0
goroutine 0 [idle]:
runtime.mach_semaphore_wait(0xf03, 0x7fff5fbff2c8, 0x10558b3, 0xffffffffffffffff, 0x1d000000000, 0x172d900, 0x7fff5fbff2f0, 0x10558b3, 0xffffffffffffffff, 0x7fff5fbff2f0, ...)
    /usr/local/go/src/runtime/sys_darwin_amd64.s:415 +0xb
runtime.semasleep1(0xffffffffffffffff, 0x7fff5fbff2f0)
    /usr/local/go/src/runtime/os_darwin.go:413 +0x4b
runtime.semasleep.func1()
    /usr/local/go/src/runtime/os_darwin.go:432 +0x33
runtime.systemstack(0x7fff5fbff318)
    /usr/local/go/src/runtime/asm_amd64.s:343 +0xab
runtime.semasleep(0xffffffffffffffff, 0x0)
    /usr/local/go/src/runtime/os_darwin.go:433 +0x4d
runtime.notesleep(0x172dd70)
    /usr/local/go/src/runtime/lock_sema.go:166 +0xb2
runtime.stopm()
    /usr/local/go/src/runtime/proc.go:1650 +0xad
runtime.findrunnable(0xc420028600, 0x0)
    /usr/local/go/src/runtime/proc.go:2102 +0x2e4
runtime.schedule()
    /usr/local/go/src/runtime/proc.go:2222 +0x14c
runtime.park_m(0xc420452340)
    /usr/local/go/src/runtime/proc.go:2285 +0xab
runtime.mcall(0x7fff5fbff4f0)
    /usr/local/go/src/runtime/asm_amd64.s:269 +0x5b
goroutine 1 [runnable]:
github.com/kardianos/govendor/context.(*Context).addSingleImport(0xc420166000, 0xc4203c96d0, 0x40, 0xc420555d81, 0xd, 0x0, 0x0, 0x1, 0x17)
    /Users/dominic/dev/src/github.com/kardianos/govendor/context/resolve.go:349 +0xd2
github.com/kardianos/govendor/context.(*Context).addFileImports(0xc420166000, 0xc4203c96d0, 0x4e, 0xc420158bc0, 0x17, 0x0, 0x0, 0xc420158bc0)
    /Users/dominic/dev/src/github.com/kardianos/govendor/context/resolve.go:238 +0x897
github.com/kardianos/govendor/context.(*Context).addSingleImport(0xc420166000, 0xc4201b4900, 0x44, 0xc42037bb91, 0x28, 0x0, 0xc420105200, 0x0, 0x0)
    /Users/dominic/dev/src/github.com/kardianos/govendor/context/resolve.go:411 +0x6de
github.com/kardianos/govendor/context.(*Context).addFileImports(0xc420166000, 0xc4201b4900, 0x56, 0xc420158bc0, 0x17, 0x0, 0x0, 0xc420158bc0)
    /Users/dominic/dev/src/github.com/kardianos/govendor/context/resolve.go:238 +0x897
github.com/kardianos/govendor/context.(*Context).addSingleImport(0xc420166000, 0xc420016d70, 0x42, 0xc42037ac31, 0x2c, 0x0, 0x0, 0x0, 0x0)
    /Users/dominic/dev/src/github.com/kardianos/govendor/context/resolve.go:411 +0x6de
github.com/kardianos/govendor/context.(*Context).addFileImports(0xc420166000, 0xc42051c550, 0x4a, 0xc420158bc0, 0x17, 0xc4200fd710, 0x0, 0x0)
    /Users/dominic/dev/src/github.com/kardianos/govendor/context/resolve.go:238 +0x897
github.com/kardianos/govendor/context.(*Context).addSingleImport(0xc420166000, 0xc420165f20, 0x49, 0xc420224b11, 0x2a, 0x0, 0x0, 0x0, 0x0)
    /Users/dominic/dev/src/github.com/kardianos/govendor/context/resolve.go:411 +0x6de
github.com/kardianos/govendor/context.(*Context).addFileImports(0xc420166000, 0xc420165f20, 0x53, 0xc420158bc0, 0x17, 0x16, 0x1, 0xc420165f20)
    /Users/dominic/dev/src/github.com/kardianos/govendor/context/resolve.go:238 +0x897
github.com/kardianos/govendor/context.(*Context).loadPackage.func1(0xc420165f20, 0x53, 0x187d070, 0xc42049bba0, 0x0, 0x0, 0xc42049bba0, 0xc420165f20)
    /Users/dominic/dev/src/github.com/kardianos/govendor/context/resolve.go:55 +0x289
github.com/kardianos/govendor/internal/vfilepath.walk(0xc420165f20, 0x53, 0x187d070, 0xc42049bba0, 0xc420158dc0, 0x0, 0x0)
    /Users/dominic/dev/src/github.com/kardianos/govendor/internal/vfilepath/walk.go:19 +0x81
github.com/kardianos/govendor/internal/vfilepath.walk(0xc4203bb7c0, 0x48, 0x187d070, 0xc42049ba00, 0xc420158dc0, 0x0, 0x0)
    /Users/dominic/dev/src/github.com/kardianos/govendor/internal/vfilepath/walk.go:44 +0x40d
github.com/kardianos/govendor/internal/vfilepath.walk(0xc4203bb3b0, 0x42, 0x187d070, 0xc42049b930, 0xc420158dc0, 0x0, 0x0)
    /Users/dominic/dev/src/github.com/kardianos/govendor/internal/vfilepath/walk.go:44 +0x40d
github.com/kardianos/govendor/internal/vfilepath.walk(0xc42051a880, 0x3a, 0x187d070, 0xc42049b790, 0xc420158dc0, 0x0, 0x0)
    /Users/dominic/dev/src/github.com/kardianos/govendor/internal/vfilepath/walk.go:44 +0x40d
github.com/kardianos/govendor/internal/vfilepath.walk(0xc4201cb4c0, 0x33, 0x187d070, 0xc4203f64e0, 0xc420158dc0, 0x0, 0x0)
    /Users/dominic/dev/src/github.com/kardianos/govendor/internal/vfilepath/walk.go:44 +0x40d
github.com/kardianos/govendor/internal/vfilepath.walk(0xc42024c1e0, 0x2f, 0x187d070, 0xc42021cea0, 0xc420158dc0, 0x0, 0x0)
    /Users/dominic/dev/src/github.com/kardianos/govendor/internal/vfilepath/walk.go:44 +0x40d
github.com/kardianos/govendor/internal/vfilepath.walk(0xc42024c060, 0x28, 0x187d070, 0xc42021cdd0, 0xc420158dc0, 0x0, 0x0)
    /Users/dominic/dev/src/github.com/kardianos/govendor/internal/vfilepath/walk.go:44 +0x40d
github.com/kardianos/govendor/internal/vfilepath.walk(0xc42013d980, 0x21, 0x187d070, 0xc4201d6a90, 0xc420158dc0, 0x0, 0x0)
    /Users/dominic/dev/src/github.com/kardianos/govendor/internal/vfilepath/walk.go:44 +0x40d
github.com/kardianos/govendor/internal/vfilepath.walk(0xc420158d80, 0x16, 0x187d070, 0xc420162dd0, 0xc420158dc0, 0x0, 0x1)
    /Users/dominic/dev/src/github.com/kardianos/govendor/internal/vfilepath/walk.go:44 +0x40d
github.com/kardianos/govendor/internal/vfilepath.Walk(0xc420158d80, 0x16, 0xc420158dc0, 0x16, 0x0)
    /Users/dominic/dev/src/github.com/kardianos/govendor/internal/vfilepath/walk.go:82 +0xd5
github.com/kardianos/govendor/context.(*Context).loadPackage(0xc420166000, 0x0, 0x0)
    /Users/dominic/dev/src/github.com/kardianos/govendor/context/resolve.go:72 +0x179
github.com/kardianos/govendor/context.(*Context).Status(0xc420166000, 0xc420083203, 0xc420166000, 0x0, 0x0, 0x8)
    /Users/dominic/dev/src/github.com/kardianos/govendor/context/status.go:259 +0x45
github.com/kardianos/govendor/run.(*runner).GoCmd(0xc42010fe78, 0x7fff5fbff701, 0x4, 0xc42000c2b0, 0x0, 0x0, 0x3c, 0xc42011b1d0, 0xc42011b1a0)
    /Users/dominic/dev/src/github.com/kardianos/govendor/run/command.go:92 +0x71
github.com/kardianos/govendor/run.(*runner).run(0xc42010fe78, 0x16f2f20, 0xc42000e018, 0xc42000c2a0, 0x2, 0x2, 0x16f22e0, 0xc42010fee7, 0x0, 0x0, ...)
    /Users/dominic/dev/src/github.com/kardianos/govendor/run/run.go:112 +0x676
github.com/kardianos/govendor/run.Run(0x16f2f20, 0xc42000e018, 0xc42000c2a0, 0x2, 0x2, 0x16f22e0, 0xc42010fee7, 0x14f6976, 0x12, 0x16f41e0)
    /Users/dominic/dev/src/github.com/kardianos/govendor/run/run.go:44 +0x8d
main.main()
    /Users/dominic/dev/src/github.com/kardianos/govendor/main.go:35 +0xe1
goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1
rax    0xe
rbx    0x172dc60
rcx    0x7fff5fbff290
rdx    0x7fff5fbff318
rdi    0xf03
rsi    0x1
rbp    0x7fff5fbff2c8
rsp    0x7fff5fbff290
r8     0x3
r9     0x0
r10    0x8
r11    0x286
r12    0x35532b7aa87
r13    0x16b48fc88318
r14    0x14d32cd5a7d64200
r15    0xc4205056c8
rip    0x105b1db
rflags 0x286
cs     0x7
fs     0x0
gs     0x0
```

**Comment by dominicbarnes** [comment]
That dump probably isn't very helpful, it doesn't appear like the process is blocked directly, but it is using a lot of CPU and never seeming to finish.
